name: Deploy Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Build and push API image 🚀
        uses: ./.github/actions/docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: api
          tag_name: 'latest'
          docker_file: ./apps/api/Dockerfile

      - name: Trigger API Deployment 🚀
        uses: indiesdev/curl@v1
        with:
          url: 'https://redeploy.heyxyz.workers.dev/?secret=${{ secrets.SECRET }}'
          method: 'GET'
          headers: '{ "Referer": "https://hey.xyz" }'
