name: Deploy Docker Images

env:
  API_RAILWAY_SERVICE_ID: 4a2a1bfb-e499-4c71-bf7f-d9ad47443c31

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: heyxyz:api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Build and push heyxyz/api:latest 🚀
        uses: ./.github/actions/docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: api
          tag_name: 'latest'
          docker_file: ./apps/api/Dockerfile

      - name: Trigger API Deployment 🚀
        uses: indiesdev/curl@v1
        id: deploy
        with:
          url: 'https://redeploy.heyxyz.workers.dev'
          params: '{ "secret": "${{ secrets.SECRET }}", "service": "${{ env.API_RAILWAY_SERVICE_ID }}" }'
          method: 'GET'
          timeout: 30000
          headers: '{ "Referer": "https://hey.xyz" }'
      - name: Deploy Status 🚀
        run: echo ${{ steps.deploy.outputs.response }}

  og:
    name: heyxyz:og
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Build and push heyxyz/og:latest 🚀
        uses: ./.github/actions/docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: og
          tag_name: 'latest'
          docker_file: ./apps/og/Dockerfile
