name: Redeploy API

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Deployment 🚀
        uses: indiesdev/curl@v1
        id: deploy
        with:
          url: 'https://redeploy.heyxyz.workers.dev/?secret=${{ secrets.SECRET }}'
          method: 'GET'
          timeout: 30000
          headers: '{ "Referer": "https://hey.xyz" }'
      - name: Deploy Status 🚀
        run: echo ${{ steps.deploy.outputs.response }}
