name: Sync Pro Accounts to Guild

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Pro Accounts to Guild
        run: |
          curl -X GET "https://api.hey.xyz/internal/pro?secret=${{ secrets.SHARED_SECRET }}"
