name: Sync to Guild

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sync-subscribers-guild:
    name: Sync Subscribers to Guild
    runs-on: ubuntu-latest
    steps:
      - name: Sync Subscribers to Guild
        run: |
          curl -X GET "https://api.hey.xyz/guild/syncSubscribers?secret=${{ secrets.SHARED_SECRET }}"

  sync-hq-score-guild:
    name: Sync HQ Score Accounts to Guild
    runs-on: ubuntu-latest
    steps:
      - name: Sync HQ Score Accounts to Guild
        run: |
          curl -X GET "https://api.hey.xyz/guild/syncHQScoreAccounts?secret=${{ secrets.SHARED_SECRET }}"

  sync-followers-standing-guild:
    name: Sync Followers Standing Accounts to Guild
    runs-on: ubuntu-latest
    steps:
      - name: Sync Followers Standing Accounts to Guild
        run: |
          curl -X GET "https://api.hey.xyz/guild/syncFollowersStanding?secret=${{ secrets.SHARED_SECRET }}"
